import os
import time
import json
import pandas as pd
import paho.mqtt.client as mqtt

# Configuration Variables
BROKER_IP = os.getenv("MQTT_BROKER_IP", "192.168.1.84") 
BROKER_PORT = int(os.getenv("MQTT_PORT", 1883))
TOPIC = "sensor/water/data"
DATASET_PATH = os.getenv("DATASET_PATH", "/app/data/simulation_test_data.csv")

PUBLISH_INTERVAL = 1.0  

# 1. Define MQTT Callbacks (Paho v2.1.0 Compliant)
def on_connect(client, userdata, flags, reason_code, properties):
    if reason_code == 0:
        print(f"[{time.strftime('%X')}] Connected to broker at {BROKER_IP}:{BROKER_PORT}")
    else:
        print(f"[{time.strftime('%X')}] Connection failed with reason code: {reason_code}")

def on_publish(client, userdata, mid, reason_code, properties):
    pass

# 2. Initialize MQTT Client
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
client.on_connect = on_connect
client.on_publish = on_publish

print(f"Connecting to Edge Broker at {BROKER_IP}...")
try:
    client.connect(BROKER_IP, BROKER_PORT, 60)
except Exception as e:
    print(f"Failed to connect to broker: {e}")
    exit(1)

client.loop_start()

# 3. Load Dataset
print(f"Loading dataset from {DATASET_PATH}...")
try:
    # Load dataset and drop NaNs. No column renaming required.
    df = pd.read_csv(DATASET_PATH).dropna()
    print(f"Dataset loaded successfully. {len(df)} valid records found.")
except Exception as e:
    print(f"Error loading CSV: {e}")
    client.loop_stop()
    exit(1)

# Features required by the Edge Pipeline
FEATURES = [
    "EXO3(Temp_C)", 
    "EXO3(spCond_uS_cm)", 
    "EXO3(pH)", 
    "SystemBattery"
]
TARGET = "EXO3(Chlorophyll_ug_L)"

# 4. The Publishing Loop
print("\nStarting Telemetry Simulation...")
print(f"Publishing 1 row every {PUBLISH_INTERVAL} second(s). Press Ctrl+C to stop.\n")

try:
    for index, row in df.iterrows():
        # Construct payload using the explicit 'date' column generated by the export script
        payload_dict = {
            "timestamp": str(row['date']),
            "features": {feature: row[feature] for feature in FEATURES},
            "ground_truth": row[TARGET]
        }
        
        # Serialize to JSON string
        payload_json = json.dumps(payload_dict)
        
        # Publish to the Pi
        client.publish(TOPIC, payload_json)
        
        print(f"Published Index {index}: {payload_json}")
        
        time.sleep(PUBLISH_INTERVAL)
        
    print("\nSimulation complete. All records published.")

except KeyboardInterrupt:
    print("\nSimulation stopped manually by user.")
finally:
    client.loop_stop()
    client.disconnect()
    print("Disconnected from broker.")