services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_edge
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    restart: unless-stopped

  sensor-sim:
    build: ../sensor-sim
    container_name: edge_sensor_sim
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1883
      - REAL_INTERVAL_SEC=900
      - TIME_SCALE_FACTOR=450
    volumes:
      - sensor_data:/data
      - ../sensor-sim/data:/app/data:ro
    restart: unless-stopped

  inference-app:
    build: ../app-v2
    container_name: edge_inference_app_v2
    depends_on:
      - mqtt_broker
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1883
      - DB_PATH=/data/sensor_data.db
      - MODEL_PATH=/data/model_v2.onnx
      - BATCH_SIZE=20
    volumes:
      - sensor_data:/data
      - ../app-v2/app.py:/app/app.py:ro
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_logs:
  sensor_data: